# Generated by Django 4.2.1 on 2023-06-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_historie_second_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historie',
            name='second_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historie',
            name='second_history_desctiption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
