# Generated by Django 4.2.1 on 2023-07-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_article_description_alter_article_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='key',
        ),
    ]
