# Generated by Django 4.2.1 on 2023-07-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_remove_article_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='NewCategorie',
        ),
    ]
