# Generated by Django 4.2.1 on 2023-07-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_delete_new_delete_newcategorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historie',
        ),
    ]
