# Generated by Django 4.2.1 on 2023-07-07 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategorie_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategorie_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='NewCategorie',
            new_name='NewsCategorie',
        ),
        migrations.CreateModel(
            name='New_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='news_images')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author_name', models.CharField(blank=True, max_length=128)),
                ('author_image', models.ImageField(blank=True, upload_to='author_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategorie')),
            ],
        ),
        migrations.CreateModel(
            name='New_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='news_images')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author_name', models.CharField(blank=True, max_length=128)),
                ('author_image', models.ImageField(blank=True, upload_to='author_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategorie')),
            ],
        ),
    ]
