# Generated by Django 4.2.1 on 2023-07-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategorie_en_newscategorie_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name_plural': 'Täzelikler'},
        ),
        migrations.AlterModelOptions(
            name='new_en',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='new_ru',
            options={'verbose_name_plural': 'Новоcти'},
        ),
        migrations.AlterModelOptions(
            name='newscategorie',
            options={'verbose_name_plural': 'Täzelikler kategoriýasy'},
        ),
        migrations.AlterModelOptions(
            name='newscategorie_en',
            options={'verbose_name_plural': 'News category'},
        ),
        migrations.AlterModelOptions(
            name='newscategorie_ru',
            options={'verbose_name_plural': 'Категорий новоcтей'},
        ),
    ]
